<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="two_dof_robot">

  <xacro:property name="base_width" value = "0.1"/>
  <xacro:property name="base_length" value = "0.1"/>
  <xacro:property name="base_height" value = "0.15"/>

  <xacro:property name="arm_width" value = "0.1"/>
  <xacro:property name="arm_length" value = "0.1"/>
  <xacro:property name="arm_height" value = "0.5"/>

  <xacro:property name="forearm_width" value = "0.1"/>
  <xacro:property name="forearm_length" value = "0.1"/>
  <xacro:property name="forearm_height" value = "0.4"/>

  <xacro:property name="link_off" value="0.1"/>

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <!-- Referencia Robot -->
  <link name="base_footprint">
  </link>

  <!-- Base Robot -->
  <link name="base_link">
    <visual>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="5" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <joint name="base_link_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <!-- Arm Robot -->
  <link name="arm_link">
    <visual>
    <origin xyz="0 0 ${arm_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${arm_length} ${arm_width} ${arm_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${arm_length} ${arm_width} ${arm_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="5" w="${arm_width}" d="${arm_length}" h="${arm_height}"/>
  </link>

  <joint name="arm_joint" type="revolute">
    <origin xyz="${link_off} 0.0 ${base_height}" rpy="0.0 0.0 0.0"/>
    <parent link="base_link"/>
    <child link="arm_link"/>
    <axis xyz="1.0 0.0 0.0"/>
    <limit lower="0.0" upper="3.15" effort="1.0" velocity="10.0"/>
  </joint>

  <!-- Forearm Robot -->
  <link name="forearm_link">
    <visual>
    <origin xyz="0 0 ${forearm_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${forearm_length} ${forearm_width} ${forearm_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
    <origin xyz="0 0 ${forearm_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${forearm_length} ${forearm_width} ${forearm_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="5" w="${forearm_width}" d="${forearm_length}" h="${forearm_height}"/>
  </link>

  <joint name="forearm_joint" type="revolute">
    <origin xyz="${-link_off} 0.0 ${arm_height}" rpy="0.0 0.0 0.0"/>
    <parent link="arm_link"/>
    <child link="forearm_link"/>
    <axis xyz="1.0 0.0 0.0"/>
    <limit lower="0.0" upper="3.15" effort="1.0" velocity="10.0"/>
  </joint>

</robot>
