diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["drivewhl_l_joint"]
    right_wheel_names: ["drivewhl_r_joint"]
    wheel_separation: 0.42
    wheel_radius: 0.05
    use_stamped_vel: false
    base_frame_id: base_footprint
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    odom_frame_id: odom
    pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
